# Generated by Django 5.2.5 on 2025-08-27 20:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_interval', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(7)])),
                ('fertilizing_interval', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(365)])),
                ('mowing_interval', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('aeration_interval', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)])),
                ('dethatching_interval', models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)])),
                ('watering_rate', models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('fertilizing_rate', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('yard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yard_preferences', to='yard_app.yard')),
            ],
        ),
    ]
