# Generated by Django 5.2.5 on 2025-09-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering', models.TextField()),
                ('tools', models.TextField()),
                ('yard_problems', models.TextField()),
                ('mowing', models.TextField()),
                ('fertilizing', models.TextField()),
                ('aerating', models.TextField()),
                ('dethatching', models.TextField()),
                ('yard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supertips', to='yard_app.yard')),
            ],
        ),
    ]
