# Generated by Django 5.2.5 on 2025-09-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supertips_app', '0001_initial'),
        ('yard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supertips',
            name='yard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supertips', to='yard_app.yard'),
        ),
    ]
