# Generated by Django 5.2.5 on 2025-08-28 20:00

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yard_app', '0002_yard_latitude_yard_longitude_alter_yard_yard_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('day_scheduled', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2025, 8, 28))])),
                ('day_completed', models.DateField(blank=True, null=True)),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='yard_app.yard')),
            ],
        ),
    ]
