# Generated by Django 5.2.5 on 2025-09-09 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('day_scheduled', models.DateField(default=datetime.date.today)),
                ('day_completed', models.DateField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=False)),
            ],
        ),
    ]

# Generated by Django 5.2.5 on 2025-09-09 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('day_scheduled', models.DateField(default=datetime.date.today)),
                ('day_completed', models.DateField(blank=True, null=True)),
                ('auto_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
