# Generated by Django 5.2.5 on 2025-09-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_app', '0001_initial'),
        ('yard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='yard_app.yard'),
        ),
    ]
