# Generated by Django 5.2.5 on 2025-09-09 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Unnamed Group', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yard_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yard_name', models.CharField(default='Unnamed Yard', max_length=100)),
                ('zip_code', models.CharField(default='Unknown', max_length=10)),
                ('yard_size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('soil_type', models.CharField(default='Unknown', max_length=20)),
                ('grass_type', models.CharField(default='Unknown', max_length=20)),
                ('longitude', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.CharField(default='Unknown', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yards', to=settings.AUTH_USER_MODEL)),
                ('yard_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yards', to='yard_app.yardgroup')),
            ],
        ),
    ]
