# Generated by Django 5.2.5 on 2025-08-28 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='latitude',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='yard',
            name='longitude',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='yard',
            name='yard_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
